# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_content', models.CharField(max_length=255)),
                ('book_image', models.ImageField(null=True, upload_to='books/images')),
            ],
        ),
    ]
