# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160526_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_note',
        ),
    ]
