# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_book_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.CharField(max_length=100),
        ),
    ]
