# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20160527_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
