# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_content', models.CharField(max_length=255)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='movies/images')),
            ],
        ),
    ]
